export default [
  "G-10",
  "E-11",
  "G-15",
  "Bani Gala",
  "DHA Defence",
  "F-11",
  "Diplomatic Enclave",
  "B-17",
  "Bhara kahu",
  "Garden Town",
  "Koral Town",
  "Soan Garden",
  "Blue Area",
  "G-11",
  "Ghauri Town",
  "I-16",
  "F-7",
  "Pakistan Town",
  "Islamabad Expressway",
  "F-6",
  "G-8",
  "Emaar Canyon Views",
  "F-17",
  "I-12",
  "F-10",
  "Bahria Town",
  "F-8",
  "G-13",
  "PWD Housing Scheme",
  "Jinnah Avenue",
  "Kuri Road",
  "Gulberg",
  "Chatha Bakhtawar",
  "I-11",
  "National Police Foundation O-9",
  "Korang Road",
  "I-8",
  "G-7",
  "Lehtarar Road",
  "G-9",
  "E-14",
  "Karakoram Diplomatic Enclave",
  "I-14",
  "D-17",
  "Tarlai",
  "Simly Dam Road",
  "I-9",
  "Burma Town",
  "Islamabad Highway",
  "The Springs",
  "Jhang Syedan",
  "Korang Town",
  "Arsalan Town",
  "Kashmir Highway",
  "I-10",
  "Pir Sohawa",
  "Ali Pur",
  "FECHS",
  "Shaheen Town",
  "H-13",
  "National Police Foundation",
  "G-14",
  "Shah Allah Ditta",
  "E-7",
  "NIH Colony",
  "7th Avenue",
  "Naval Anchorage",
  "Margalla Town",
  "Tarnol",
  "H-15",
  "D-13",
  "CBR Town",
  "Meherban Colony",
  "Zaraj Housing Scheme",
  "Multi Residencia & Orchards",
  "Capital Enclave",
  "G-16",
  "PWD Road",
  "Jhangi Syedan",
  "Taramrri",
  "E-16",
  "Khanna Pul",
  "Islamabad - Murree Expressway",
  "PAEC Employees Cooperative Housing Society",
  "D-12",
  "Green Avenue",
  "9th Avenue",
  "E-18",
  "Golra Mor",
  "Shahpur",
  "Chak Shahzad",
  "Motorway Chowk",
  "Spring Valley",
  "GT Road",
  "Gulshan-e-Khudadad",
  "H-12",
  "River Garden",
  "G-12",
  "Faisal Town - F-18",
  "Al Huda Town",
  "I-13",
  "Qutbal Town",
  "Alipur Farash",
  "C-18",
  "Royal City",
  "Airport Enclave",
  "F-9",
  "Shehzad Town",
  "Rawal Enclave",
  "IJP Road",
  "Madina Town",
  "Iqbal Town",
  "Wapda Town",
  "Rawal Town",
  "Frash Town",
  "Swan Garden",
  "Thalian",
  "Thanda Pani",
  "Zero Point",
  "New Shakrial",
  "Sihala",
  "PAF Tarnol",
  "F-15",
  "G-6",
  "Green Hills Housing Scheme",
  "AGHOSH",
  "Koral Chowk",
  "PECHS",
  "Judicial Town",
  "G-5",
  "Sarai Kharbuza",
  "Japan Road",
  "Marwa Town",
  "D-14",
  "Mumtaz City",
  "Lawyers Society",
  "D-18",
  "E-12",
  "Chattar",
  "Sohan Valley",
  "Ibn-e-Sina Road",
  "Kahuta Triangle Industrial Area",
  "Azmat Town",
  "Park Road",
  "Partal Town",
  "Pindorian",
  "Abdullah Garden",
  "C-14",
  "Ataturk Avenue",
  "Phulgran",
  "Fateh Jang Road",
  "Royal Avenue",
  "Bokra Road",
  "Park Enclave",
  "H-11",
  "Murree Road",
  "Police Foundation Housing Society",
  "C-19",
  "Park View City",
  "Top City 1",
  "Agha Shahi Avenue",
  "Jagiot Road",
  "Others",
  "Akbar Town",
  "PTV Colony",
  "Zone 5",
  "Tumair",
  "12th Avenue",
  "Federal Government Employees Housing Foundation",
  "Al Qaim Town",
  "Kuri Model Town",
  "Golra Road",
  "Sangjani",
  "Athal",
  "Aiza Garden",
  "University Town",
  "Victoria Heights",
  "Islamabad, Islamabad Capital",
  "Islamabad View Valley",
  "New Airport Town",
  "Kuri",
  "Raja Akhtar Road",
  "Nazim-ud-din Road",
  "Airport Avenue Housing Society",
  "Kahuta Road",
  "Pakistan Intelligence Bureau Housing Society",
  "Ahmed Town",
  "Embassy Road",
  "Khayaban-e-Iqbal",
  "Engineering Co-operative Housing (ECHS)",
  "NHA Housing Society",
  "Central Avenue",
  "Airline Avenue",
  "H-8",
  "Model Town",
  "Sihala Valley",
];
