export default [
  "DHA Defence",
  "Malir",
  "Gadap Town",
  "Gulshan-e-Iqbal Town",
  "Scheme 33",
  "Cantt",
  "Abul Hassan Isphani Road",
  "Shahra-e-Faisal",
  "Gizri",
  "Saddar Town",
  "Gulistan-e-Jauhar",
  "Federal B Area",
  "North Karachi",
  "Bahria Town Karachi",
  "Jinnah Avenue",
  "PAF Housing Scheme",
  "Northern Bypass",
  "Fazaia Housing Scheme",
  "North Nazimabad",
  "New Karachi",
  "Anda Mor Road",
  "Clifton",
  "Lyari Town",
  "Bath Island",
  "Falcon Complex Faisal",
  "Jamshed Town",
  "Defence View Society",
  "Nazimabad",
  "P & T Colony",
  "Navy Housing Scheme Karsaz",
  "Baldia Town",
  "Gulshan-e-Usman Housing Society",
  "Garden West",
  "Liaquatabad",
  "Zamzama",
  "Chapal Uptown",
  "Baloch Colony",
  "Manzoor Colony",
  "Delhi Colony",
  "Airport",
  "University Road",
  "Shah Faisal Town",
  "Falaknaz Presidency",
  "Bin Qasim Town",
  "Hill Park",
  "Malir Link To Super Highway",
  "Gulberg Town",
  "Super Highway",
  "Khalid Bin Walid Road",
  "Azam Town",
  "Korangi",
  "Shaheed Millat Road",
  "Saima Luxury Homes",
  "Rabia City",
  "M. A. Jinnah Road",
  "Mehmoodabad",
  "Suparco Road",
  "Rufi Rose Petals",
  "Punjab Chowrangi",
  "Khaliq-uz-Zaman Road",
  "Orangi Town",
  "Gulshan-e-Areesha",
  "Sea View Apartments",
  "Kashmir Road",
  "Dastgir Colony",
  "Rashid Minhas Road",
  "Defence Garden",
  "Sindh Industrial Trading Estate (SITE)",
  "Britto Road",
  "Tariq Road",
  "KDA Scheme 1",
  "Saadi Road",
  "Jamshed Road",
  "Landhi",
  "Gulshan-e-Amin",
  "Manghopir Road",
  "Nishtar Road (Lawrence Road)",
  "Al-Hilal Society",
  "National Highway",
  "Maqboolabad Society",
  "Frere Town",
  "Falaknaz Dynasty",
  "Etawa Society",
  "Liaquat Avenue",
  "MT Khan Road",
  "Aisha Manzil",
  "Abid Town",
  "Karachi Motorway",
  "Surti Muslim Co-Operative Housing Society",
  "ASF Housing Scheme",
  "Muslimabad Society",
  "Civil Lines",
  "Khuda Ki Basti",
  "Hawks Bay Scheme 42",
  "Cotton Export Cooperative Housing Society",
  "Kamran Chowrangi",
  "Gizri Road",
  "Peoples Colony",
  "Lyari Expressway",
  "Bilal Town",
  "Scheme 45",
  "Shaheed-e-Millat Expressway",
  "Amir Khusro",
  "DHA City Karachi",
  "Sakhi Hassan Chowrangi",
  "Naval Colony",
  "Kemari Town",
  "BMCHS",
  "Punjab Colony",
  "ASF Tower",
  "Lines Area",
  "Golimar",
  "Tipu Sultan Road",
  "Korangi Road",
  "Lalukhet",
  "Shah Town",
  "Pakistan Chowk",
  "Cutchi Memon Cooperative Housing Society",
  "Rufi Lake Drive Apartments",
  "Gobal Town",
  "Guru Mandir Chorangi",
  "Naya Nazimabad",
  "Khayaban-e-Ittehad Road",
  "Teacher Society",
  "Maskan Chowrangi",
  "Old Queens Road",
  "Shadman 2",
  "Shahra-e-Qaideen",
  "PTV Society",
  "Dalmia Cement Factory Road",
  "Gulshan-e-Umair",
  "Mauripur Road",
  "Khudadad Colony",
  "I. I. Chundrigar Road",
  "Qayyumabad",
  "Chapal Courtyard",
  "Dr Daud Pota Road",
  "circular road",
  "Al-Safaa Garden",
  "Intelligence Colony",
  "Cosmopolitan Society",
  "Stadium Road",
  "State Bank of Pakistan Staff Co-Operative Housing Society",
  "Shahra-e-Usman",
  "Kashmir Colony",
  "Shahrah-e-Pakistan",
  "Numaish Chowrangi",
  "Abdullah Haroon Road",
  "Gujjar Chowk",
  "Hub River Road",
  "Al-Manzar Society",
  "Royal Defence Tower",
  "Old Clifton",
  "Javed Bahria Coopretive Housing Society",
  "Siraj-ud-Daula Road",
  "Chapal Skymark",
  "Gulshan-e-Jami",
  "Gadap Road",
  "Gulshan-E-Faisal",
  "Ranchore Line Bazar",
  "Gulshan-e-Malir",
  "Laraib Garden",
  "Naval Housing Scheme",
  "PIDC",
  "Sher Shah Suri Road",
  "Diamond City",
  "Times Residency",
  "Teachers Society",
  "Nooriabad",
  "Police Society",
  "Altaf Hussain Road",
  "Al-Jadeed Residency",
  "Old Ravians Co-Operative Housing Society",
  "Gulshan-e-Millat",
  "Beaumont Road",
  "Amil Colony",
  "Malir Housing Scheme 1",
  "Karachi, Sindh",
  "Hoshang Road",
  "Allama Iqbal Town",
  "Bagh-e-Korangi",
  "Gulistan-e-Malir",
  "Shahra-e-Jahangir",
  "Erum Villas",
  "Catholic Colony",
  "Humaira Town",
  "Hassan Goth",
  "Jamaluddin Afghani Road",
  "Karachi Golf City",
  "Others",
  "Mangopir",
  "Damba",
  "Shahra-e-Liaquat",
];
