export default [
  "Multan Road",
  "Allama Iqbal Town",
  "Military Accounts Housing Society",
  "Eden",
  "Askari",
  "Bedian Road",
  "Gulberg",
  "Chaman Park",
  "Chungi Amar Sadhu",
  "Karim Park",
  "Cantt",
  "Al-Raheem Garden",
  "EME Society",
  "Mateen Avenue",
  "Paragon City",
  "IEP Engineers Town",
  "Bahria Town",
  "Architects Engineers Housing Society",
  "DHA Defence",
  "Samanabad",
  "Mozang",
  "Model Town",
  "Sultan Pura",
  "T & T Aabpara Housing Society",
  "Al Faisal Town",
  "Gulshan-e-Ravi",
  "Canal Garden",
  "Muslim Nagar Housing Scheme",
  "Tricon Village",
  "PCSIR Housing Scheme",
  "Pak Arab Housing Society",
  "State Life Housing Society",
  "DHA 11 Rahbar",
  "Shershah Colony - Raiwind Road",
  "Jaranwala Road",
  "Cavalry Ground",
  "Cricketer Villas",
  "Rehman Villas",
  "Faisal Town",
  "Harbanspura Road",
  "Alfalah Town",
  "Punjab Govt Employees Society",
  "Ashiana-e-Quaid Housing Scheme",
  "Shalimar Housing Scheme",
  "Khayaban-e-Amin",
  "Shahdara",
  "Iqbal Park",
  "Sabzazar Scheme",
  "Model Colony",
  "Mustafa Town",
  "Walton Road",
  "New Super Town",
  "West Wood Housing Society",
  "Valencia Housing Society",
  "Palm Villas",
  "Islampura",
  "Mansoorah",
  "Marghzar Officers Colony",
  "Wapda Town",
  "Mughalpura",
  "Saggian",
  "Shoukat Town",
  "Al Hamra Town",
  "Badami Bagh",
  "Gulistan Colony",
  "Lahore Motorway City",
  "OPF Housing Scheme",
  "Garden Town",
  "Ferozepur Road",
  "Township",
  "Babu Sabu",
  "Al Kareem Garden",
  "Nawab Town",
  "Johar Town",
  "Punjab Small Industries Colony",
  "Shalimar Link Road",
  "Airline Housing Society",
  "Airport Road",
  "Kamahan Road",
  "Mehmood Booti",
  "Kot Lakhpat",
  "Pakki Thatti",
  "Canal View",
  "Al-Hafiz Town",
  "Gulshan-e-Lahore",
  "Qadri Colony",
  "Tariq Gardens",
  "Hameedpura",
  "Empress Road",
  "Khayaban-e-Jinnah Road",
  "Ahmad Housing Society",
  "Jallo Park Road",
  "Green Cap Housing Society",
  "Bismillah Housing Scheme",
  "Fateh Garh",
  "GT Road",
  "Jubilee Town",
  "Park View Villas",
  "Sant Nagar",
  "Al Rehman Garden",
  "Harbanspura",
  "Lalazar",
  "Ashraf Garden",
  "Al-Kabir Town",
  "Nishat Colony",
  "College Road",
  "Aashiana Road",
  "Ali View Park",
  "Divine Gardens",
  "Rail Town (Canal City)",
  "Bahria Nasheman",
  "Ghaziabad",
  "Kahna",
  "Doctors Housing Society",
  "Vital Homes Housing Scheme",
  "Bilal Gunj",
  "Taj Bagh Scheme",
  "Gohawa",
  "Rehmanpura (Ferozpur Road)",
  "Shadipura",
  "Swami Nagar",
  "Baghbanpura",
  "Nasheman-e-Iqbal",
  "Lake City",
  "AWT Army Welfare Trust",
  "Shadbagh",
  "Eden Villas",
  "Sui Gas Housing Society",
  "Misri Shah",
  "Thokar Niaz Baig",
  "Lahore Medical Housing Society",
  "UBL Housing Society",
  "Salli Town",
  "PIA Main Boulevard",
  "Nishtar Colony",
  "Bhatta Chowk",
  "Madina Colony",
  "Highcourt Society",
  "Ravi Park",
  "Zaman Colony",
  "Raiwind Road",
  "Central Park Housing Scheme",
  "Mohafiz Town",
  "Awan Town",
  "Shadab Garden",
  "Al Rahim Homes",
  "Chauburji Chowk",
  "Islamia Park",
  "Abdalians Cooperative Housing Society",
  "Sunny Park",
  "Fort Villas",
  "Izmir Town",
  "PIA Housing Scheme",
  "Dream Avenue Lahore",
  "Mehar Fayaz Colony",
  "Al-Amin Housing Society",
  "Upper Mall",
  "Defence Road",
  "Dharampura",
  "Hassan Town",
  "Lalazaar Garden",
  "Eden Place Housing Scheme",
  "Sukh Chayn Gardens",
  "BOR - Board of Revenue Housing Society",
  "Afzal Park",
  "Naz Town",
  "Green Town",
  "Jewa Town",
  "Ahbab Colony",
  "Shahkam Chowk",
  "Walled City",
  "Asif Colony",
  "Outfall Road",
  "Bagarian",
  "Jinnah Colony",
  "Sajid Garden",
  "Salamatpura",
  "Sham Nagar",
  "River View Coop Housing Society",
  "Bahar Shah Road",
  "Ring Road",
  "Rehan Garden",
  "Ittifaq Town",
  "Shalimar Town",
  "Al Hafeez Gardens",
  "Canal Bank Housing Scheme",
  "Bahria Orchard",
  "Shershah Colony - Ichra",
  "Al-Hamd Garden",
  "Audit & Accounts Housing Society",
  "Aabpara Coop Housing Society",
  "Beacon House Society",
  "Khayaban-e-Quaid",
  "Manawan",
  "Bhagatpura",
  "PCSIR Staff Colony",
  "Canal Burg",
  "Azam Gardens",
  "Daroghewala",
  "Tajpura",
  "Chohan Road",
  "Garhi Shahu",
  "Wassanpura",
  "Ghous Garden",
  "Kacha Jail Road",
  "Sanda",
  "Revenue Society",
  "New Shah Kamal Colony",
  "Dogech",
  "Muslim Town",
  "Rehman Gardens",
  "Kacha Ferozepur Road",
  "Band Road",
  "New Chauburji Park",
  "Punjab Govt Servant Society",
  "Zaheer Villas",
  "Bhogiwal Road",
  "Omega Homes",
  "Al Jalil Garden",
  "Gajju Matah",
  "Rizwan Garden Scheme",
  "Peco Road",
  "Begampura",
  "Mohlanwal",
  "Shah Jamal",
  "Gul Kali",
  "Raj Garh",
  "Eden Avenue Extension",
  "Habib Homes",
  "Lahore Canal Bank Cooperative Housing Society",
  "Riwaz Garden",
  "Manga Mandi",
  "Formanites Housing Scheme",
  "Sally Town South",
  "Al-Kareem Premier Housing Scheme",
  "Zaitoon - New Lahore City",
  "Jaffar Town",
  "Punjab Coop Housing Society",
  "Fazaia Housing Scheme",
  "Anarkali",
  "Sodiwal",
  "Shiraz Villas",
  "Shah Faisal Road",
  "Ichhra",
  "Dubai Town",
  "Farooq Colony",
  "Ali Alam Garden",
  "New Muslim Town",
  "Main Canal Bank Road",
  "Allama Iqbal Intl Airport",
  "Lahore Press Club Housing Scheme",
  "Peer Colony",
  "Jora Pull",
  "Royal Garden",
  "Super Town",
  "Shera Kot",
  "Bait-ul-Raza Colony",
  "Hamza Town",
  "Real Cottages",
  "Sue-e-Asal",
  "Garrison Homes",
  "Al-Falah Cooperative Housing Society",
  "Makkah Colony",
  "Pak Park",
  "Wahdat Road",
  "Punjab University Employees Society",
  "Ahmad Avenue",
  "Sufiabad",
  "Judicial Colony",
  "Al Noor Town",
  "Gosha-e-Ahbab",
  "Faiz Bagh",
  "Al Jannat Housing Scheme",
  "Manzoor Colony",
  "Jaffaria Colony",
  "Lahore Garden Housing Scheme",
  "Walton Railway Officers Colony",
  "Jallo",
  "Gulfishan Colony",
  "LDA Avenue",
  "Abid Market",
  "Shadman 2",
  "Saggian Wala Bypass Road",
  "Gul-e-Damin",
  "PASSCO Housing Society",
  "P & D Housing Society",
  "Sheraz Town",
  "Sher Shah Road",
  "Gulshan Park",
  "Mohlanwal Road",
  "Zubaida Park",
  "Clifton Colony",
  "Al-Hamd Park",
  "Temple Road",
  "Rehman City - Phase 4",
  "Nai Abadi Harbanspura",
  "Education Town",
  "Khokhar Town",
  "Sarwar Town",
  "Abdali Road",
  "Kalma Chowk",
  "Rustam Park",
  "Kotli Abdur Rahman",
  "Grand Avenues Housing Scheme",
  "Chaudhary Park",
  "Kharak",
  "Canal Fort II",
  "AR Cottages",
  "Fateh Villas",
  "Combo Colony",
  "NFC 1",
  "Hakim Town",
  "Lower Mall",
  "Qazi Town",
  "Hanif Park Harbanspura",
  "Sanda Road",
  "Mustafa Abad",
  "Siddiqia Colony",
  "China Scheme",
  "Bankers Co-operative Housing Society",
  "Waris Colony",
  "Bahar Colony",
  "Rasool Park",
  "Krishan Nagar",
  "UET Housing Society",
  "Alia Town",
  "Waris Road",
  "Chauburji Park Road",
  "Asim Town",
  "Chinar Bagh",
  "Sheikhupura Road",
  "Islam Nagar",
  "Abdul Sattar Edhi Road",
  "Heaven Homes",
  "Kot Khawaja Saeed",
  "Kachupura",
  "Hajvery Housing Scheme",
  "Makki Complex",
  "Sultan Town",
  "Ameer-ud-Din Park",
  "Manga - Raiwind Road",
  "Millat Colony",
  "Wafaqi Colony",
  "Youhanabad",
  "Kahna Kacha",
  "Cantt View Society",
  "Government Employees Cooperative Housing Society (GECHS)",
  "Al Fajar Society",
  "Lawrence Road",
  "Shah Di Khoi",
  "Jail Road",
  "Rajpoot Town",
  "Shahpur Kanjra",
  "Hanjarwal",
  "Shah Kamal Road",
  "Chah Miran",
  "Allama Iqbal Road",
  "Sherwani Town Housing Scheme",
  "Elite Town",
  "Green City",
  "Malik Park",
  "Saidpur",
  "Azadi Chowk",
  "Rana Town",
  "Ameen Park",
  "Dholanwal",
  "Sitara Colony",
  "Canalberg Housing Society",
  "Lytton Road",
  "Lahore - Jaranwala Road",
  "Nasirabad",
  "Nadeem Town",
  "Singhpura",
  "Al Hamad Colony",
  "Zaitoon Colony",
  "Nazir Garden Society",
  "Mian Colony",
  "TIP Housing Society",
  "Madina Town",
  "Sahafi Colony",
  "Royal Residencia",
  "Shadman 1",
  "Khaira",
  "Ravi Road",
  "Aitchison Society",
  "Gawala Colony",
  "Nizamabad",
  "Islamabad Colony",
  "Ashrafi Town",
  "Lakhodher",
  "Wyeth Employees Coop Housing",
  "Dream Villas",
  "Habibullah Road",
  "Ittehad Colony",
  "Ibrahim Colony",
  "Al Haram Garden",
  "Jia Baga Road",
  "Karbath",
  "Guldasht Town",
  "Qartaba Chowk",
  "Wahdat Colony",
  "Wocland Villas",
  "Davis Road",
  "National Town",
  "Ali View Garden",
  "Rajgarh Road",
  "Prem Nagar",
  "Immad Garden Housing Scheme",
  "Jan Muhammad Road",
  "Labor Colony",
  "Aman Town",
  "Agrics Town",
  "Mall Road",
  "Lahore - Islamabad Motorway",
  "Al-Hamad Colony (AIT)",
  "DHA City",
  "Haji Park Housing Scheme",
  "Bhaini Road",
  "Lahore - Kasur Road",
  "Toheed Park",
  "Ghausia Colony",
  "Jamil Town",
  "Eden Park",
  "Land Breeze Housing Society",
  "Acro Green - Bankers Avenue",
  "Data Ganj Bakhsh Town",
  "Azeem Garden Shahdara",
  "Nisbat Road",
  "Siddiqia Society (College Road)",
  "Altaf Colony",
  "Tariq Ismail Road",
  "Atari Saroba",
  "Mason Road",
  "Dubban Pura",
  "Excise & Taxation Housing Scheme",
  "Sami Town",
  "Gulbahar Park",
  "Nadeem Shaheed Road",
  "Green Acres Housing Society",
  "UMT Society",
  "Gulbahar Colony",
  "Chaudhary Colony",
  "Jati Umra Road",
  "Prime Homes 1",
  "Pir Naseer",
  "Gujjarpura",
  "Nayyab Villas",
  "New Canal Park",
  "Qasurpura",
  "Gulshan-E-Mustafa Housing Society",
  "Nain Sukh",
  "Mian Amiruddin Park",
  "Malipura",
  "GOR",
  "Khana Kacha Road",
  "Alpha Society",
  "Saman Berg",
  "Green Park",
  "Bahadurabad",
  "Poonch Road",
  "Mominpura Road",
  "Angoori Bagh",
  "Madina Homes",
  "Race Course Road",
  "Shama Road",
  "Iqbal Avenue",
  "Shanghai Road",
  "HBFC Housing Society",
  "Mushtaq Park - Phase 3",
  "Saqib Town",
  "Qilla Gujjar Singh",
  "Wapda Colony",
  "Rehmanpura (Harbanspura)",
  "Public Health Society",
  "Bhogiwal",
  "Shah Khawar Town",
  "Gulshan-e-Ahbab",
  "NFC 2",
  "Adan Villas",
  "McLeod Road",
  "Gulshan-e-Yaseen Housing Society",
  "Saroba Gardens Housing Society",
  "Al-Wahab Garden - Phase 1",
  "Green Park Society",
  "Gulshan Colony",
  "LDA City",
  "Rifle Range Road",
  "Cooper Road",
  "Ferozepur City",
  "Railway Officers Colony",
  "Batapur",
  "Sunfort Gardens",
  "Gawalmandi",
  "Montgomery Road",
  "Jalal Colony",
  "Venus Housing Scheme",
  "Saadi Park",
  "Supreme Villas",
  "Civil Defence",
  "Javed Colony - Ghazi Road",
  "Faisal Ghuman Road",
  "Yazdani Road",
  "Sunderdas Road",
  "Sharaqpur Road",
  "Abu Alkhair Road",
  "Asif Town",
  "PAF Society",
  "Firdous Colony",
  "Samsani Road",
  "Gulfishan Town",
  "Sozo Town",
  "Lahore, Punjab",
  "Mian Mir Colony",
  "Munir Garden",
  "IBL Housing Scheme",
  "Khayaban-e-Zohra",
  "Expo Avenue Society",
  "Jamal Homes",
  "Queens Road",
  "Rang Mahal",
  "Ali Town",
  "Millat Road",
  "Gul Colony",
  "Noor Jahan Road",
  "Al-Jannat Housing Society - Kahna",
  "Al Madina Avenue",
  "Shahtaj Colony",
  "Gulshan Farooq Scheme",
  "TECH Society",
  "Sui Gas Employees Cooperative Housing Society",
  "Tarogill",
  "Rehman Housing Society",
  "Divine Homes",
  "Officer Colony",
  "Heir",
  "Saadat Avenue",
  "Irrigation Cooperative Housing Society",
  "Gujjar Colony",
  "Mominpur",
  "Defence Garden",
  "Beadon Road",
  "Nabha Road",
  "Lahore Villas",
  "Rehman Park",
  "Ahlu Road",
  "Infantry Road",
  "Muqaddas Park",
  "Mian Aziz Garden",
  "Chauburji",
  "Farid Court Road",
  "Hudiara",
  "Mohni Road",
  "Liaquatabad",
  "Abdullah Town",
  "Katar Bund Road",
  "Al-Raziq Garden",
  "Gulshan View Residence Society",
  "Bahria Education & Medical City",
  "Tulspura",
  "Sunflower Housing Society",
  "Bhatti Colony",
  "Sadaat Town",
  "Rewaz Garden",
  "Shuja Road",
  "New Samanabad",
  "Bankers Town",
  "Gulzar E Ahbab Society",
  "Gulnishan Park",
  "Others",
  "Begum Kot",
  "Al-Hafeez Garden Road",
  "Mateen Garden",
  "Sultan Colony",
  "Defence Fort",
];
